### PR TITLE
Enable client Konflux generator

### PR DESCRIPTION
**Pull request by dsimansk**
Per title & bump OCP version.

/cc @creydr @pierDipi

### CODE REVIEW

**Comment by pierDipi** [comment]
```
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-test-sidecarcontainer is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-kn is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-test-servingcontainer is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-test-grpc-ping is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-source-image is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-cli-artifacts is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:knative-client-test-helloworld is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=error error="output tag openshift/knative-v1.15:client-src is promoted from more than one place: openshift-knative/client@release-v1.15 [416], openshift-knative/client@release-v1.15 [415]"
time="2024-10-17T11:35:28Z" level=fatal msg="error validating configuration files"
```

**Comment by dsimansk** [comment]
@pierDipi how do a drop 4.15 variant then?

**Comment by dsimansk** [comment]
I don't see anything specific e.g. in this PR: https://github.com/openshift-knative/hack/pull/296

**Comment by dsimansk** [comment]
> I don't see anything specific e.g. in this PR: #296

Nevermind I see there will be an issue with ignore config.

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
