### PR TITLE
Switch to non oci-ta docker build pipeline

### PR DESCRIPTION
**Pull request by creydr**
As discussed switching to the "default" docker pipeline until we have figured out the build issues

### CODE REVIEW

**Comment by pierDipi** [comment]
/hold

tests failing

**Comment by creydr** [comment]
> tests failing

missed the update in konfluxgen.go: https://github.com/openshift-knative/hack/compare/1ebb0095c2c67d1735373fb93210b37ee39c5734..2ae983cd3fb0c46ab89c550ceb3903b897444049

**Pull request merged**
