### PR TITLE
Remove old branches

### PR DESCRIPTION
**Pull request by skonto**
- replace #90 
- output:
```
 git status
On branch sync-serverless-ci
Your branch is up to date with 'master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__412.yaml -> ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__414.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8__410.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8__413.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6__412.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6__48.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7__412.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7__48.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8__410.yaml
	deleted:    ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8__413.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.6__412.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.6__48.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.7__412.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.7__48.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.8__410.yaml
	deleted:    ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.8__413.yaml
	deleted:    ci-operator/config/openshift-knative/net-istio/openshift-knative-net-istio-release-1.8.yaml
	deleted:    ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.8.yaml
	deleted:    ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__410.yaml
	deleted:    ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__413.yaml
	modified:   ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-periodics.yaml
	modified:   ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-postsubmits.yaml
	modified:   ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.8-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.8-presubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-periodics.yaml
	deleted:    ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-postsubmits.yaml
	deleted:    ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-presubmits.yaml
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.6_eventing-kafka-broker_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.6_eventing_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.7_eventing-kafka-broker_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.7_eventing_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.8_eventing-istio_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.8_eventing-kafka-broker_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.8_eventing_quay
	deleted:    core-services/image-mirroring/knative/mapping_knative_knative-v1.8_serving_quay


```

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
This is awesome 🥳  Way more readable than the other version!

/lgtm
/approve

/hold for @pierDipi to also take a look
/assign @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
https://github.com/openshift-knative/hack/actions/runs/6954333218

**Pull request merged**
