### PR TITLE
Bump cluster pool for Serverless >=1.35 to OCP 4.17

### PR DESCRIPTION
**Pull request by mgencur**
Not touching settings for branches 1.34 and older.

/hold
Depends on https://github.com/openshift/release/pull/58495

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
(free to unhold)

**Comment by pierDipi** [comment]
@mgencur there is a conflict

**Comment by mgencur** [comment]
Resolved the conflict.
This PR still depends on https://github.com/openshift/release/pull/58508 (and on me verifying it's working). So holding for now. But these are ready for review. Thanks!

/hold

**Pull request merged**
