### PR TITLE
:gift: Gather licenses

### PR DESCRIPTION
**Pull request by cardil**
Gather licenses to fix the HasLicense from ecosystem-cert-preflight-checks task.

### CODE REVIEW

**Comment by matejvasek** [comment]
Would you please add it also the the func template?

**Comment by cardil** [comment]
> Would you please add it also the the func template?

After the merge, we need to update all the fork repos.

**Comment by matejvasek** [comment]
`GOFLAGS='-tags strictfipsruntime,exclude_graphdriver_btrfs'` =>
`GOFLAGS='-tags=strictfipsruntime,exclude_graphdriver_btrfs'`

**Comment by matejvasek** [comment]
cc @creydr

**Comment by cardil** [comment]
/close 

See https://github.com/openshift-knative/hack/pull/424

**Pull request closed without merging**
