### PR TITLE
Add new midstream branches

### PR DESCRIPTION
**Pull request by serverless-qe**
Discover new branches using openshift-knative/hack.

### CODE REVIEW

**Comment by ReToCode** [comment]
We don't want 1.13 CI because these branches are not needed. @mgencur I expect this is going to be recreated when I close it? @skonto so we might need to rename the branches?

**Comment by pierDipi** [comment]
> @mgencur I expect this is going to be recreated when I close it?

Yes, @ReToCode

**Comment by ReToCode** [comment]
I did rename the branches, so this should be fine with closing.

**Pull request closed without merging**
