### PR TITLE
Preserve newer Tekton task images in Konflux pipelines

### PR DESCRIPTION
**Pull request by pierDipi**
This handles the case task images are updated with renovate, like in https://github.com/openshift-knative/eventing-istio/pull/273

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by creydr** [comment]
This is great. Thanks a lot!

**Comment by pierDipi** [comment]
One further issue is that https://github.com/openshift-knative/eventing-istio/pull/273 updates on release-next will not be preserved but that's a bit the nature of release next :(

**Comment by creydr** [comment]
I though about excluding the main branch from this logic, and running the updating the pipeline definition file (https://github.com/openshift-knative/hack/blob/main/pkg/konfluxgen/docker-build.yaml) each time. So we have the latest tags on main / release-next, but ignore them on the release branches.
To not run the renovate jobs on release-next (like https://github.com/openshift-knative/eventing-istio/pull/273), we could check to configure a renovate.json and disable it for this branch

**Pull request merged**
