### PR TITLE
[main] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by mgencur** [comment]
@creydr Do we need to apply this manually in Gitlab?

**Comment by creydr** [comment]
> @creydr Do we need to apply this manually in Gitlab?

We need to manually copy them (for now) to [gitlab](https://gitlab.cee.redhat.com/releng/konflux-release-data/-/tree/main/config/stone-prd-rh01.pg1f.p1/product/ReleasePlanAdmission/ocp-serverless). I'll do it...

**Comment by mgencur** [comment]
@creydr Thanks!

**Comment by creydr** [comment]
@mgencur: https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/2774

**Pull request merged**
