### PR TITLE
:lady_beetle: [kn-event] Proper unit tests target

### PR DESCRIPTION
**Pull request by cardil**
## Changes

- :lady_beetle: Proper Makefile target for unit tests for kn-event

See the target: 

https://github.com/openshift-knative/kn-plugin-event/blob/41fbdb9642d1ee516af1043a8efa4ee523656904/Makefile#L14-L16

### CODE REVIEW

**Comment by dsimansk** [comment]
As an example, we have deferred unit tests in S-O to gh actions. It's actually super quick to execute in comparison to OpenShift CI. Just an ides how to approach it from different side.

**Comment by cardil** [comment]
The unit tests on Openshift CI are also fairly quick. They don't take much resources and time, and are executed in parallel with e2e tests, so they aren't the real problem IMHO.

**Pull request merged**
