### PR TITLE
Update CI config to use OpenShift 4.12

### PR DESCRIPTION
**Pull request by aliok**
Only for 1.6+ versions of components

### CODE REVIEW

**Comment by aliok** [comment]
/hold 

Holding until https://docs.ci.openshift.org/docs/how-tos/cluster-claim/#existing-cluster-pools has 4.12 pool

**Comment by aliok** [comment]
/unhold

I see 4.12 available in that document

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
Thanks for the README update as well!

**Pull request merged**
